apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: django
  labels:
    app: django
spec:
  replicas: 1
  selector:
    matchLabels:
      pod: django
  template:
    metadata:
      labels:
        pod: django
    spec:
      containers:
        - name: django
          image: wischlabs/locality_finder:latest
          imagePullPolicy: Always
          volumeMounts:
            - name: nginx-static-pv
              mountPath: /code/static
            - name: nginx-media-pv
              mountPath: /code/media
          ports:
            - containerPort: 8000
          env:
            - name: POSTGRES_USER
              value: docker
            - name: POSTGRES_PASSWORD
              value: docker
            - name: POSTGRES_DBNAME
              value: docker
            - name: DJANGO_SETTINGS_MODULE
              value: settings.k8s_settings

      volumes:
        - name: nginx-static-pv
          persistentVolumeClaim:
            claimName: nginx-static-pvc
        - name: nginx-media-pv
          persistentVolumeClaim:
            claimName: nginx-media-pvc
