apiVersion: batch/v1
kind: Job
metadata:
  name: django-migrations
spec:
  template:
    spec:
      containers:
        - name: django
          image: wischlabs/locality_finder:latest
          command: ['python', 'manage.py', 'migrate']
          env:
            - name: POSTGRES_USER
              value: docker
            - name: POSTGRES_PASSWORD
              value: docker
            - name: POSTGRES_HOST
              value: postgis-service
            - name: DJANGO_SETTINGS_MODULE
              value: settings.k8s_settings
      restartPolicy: Never
  backoffLimit: 5