language: python
python:
    - "3.8-dev"
    - "3.7"
    - "3.6"
    - "3.5"
    - "3.4"
    - "2.7"
    - "1.6"
    - "1.5"
    - "1.4"

services:
  - docker

env:
    - DJANGO_VERSION=3.0a1
    - DJANGO_VERSION=2.2
    - DJANGO_VERSION=2.1
    - DJANGO_VERSION=2.0
    - DJANGO_VERSION=1.11

install:
    - pip install -q -r requirements.txt
    - pip install -q -r docker_requirements.txt
    - pip install -q Django==$DJANGO_VERSION

script:
    - docker-compose up -d
    - docker-compose exec web coverage run manage.py test
