version: '3'

services:
  db:
    image: kartoza/postgis
    environment:
      - ALLOW_IP_RANGE=0.0.0.0/0
      - POSTGRES_USER=docker
      - POSTGRES_PASS=docker
      - POSTGRES_DBNAME=docker
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - db_network
  web:
    build:
      context: .
      dockerfile: Dockerfile_Compose
    environment:
      - DJANGO_SETTINGS_MODULE=settings.docker_settings
    #command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; gunicorn locality_finder.wsgi --bind :8080'
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; python manage.py runserver 0.0.0.0:8080'
    volumes:
      - .:/code
      - static_volume:/code/static
      - media_volume:/code/media
    networks:
      - db_network
      - nginx_network
    depends_on:
      - db
  nginx:
    image: nginx:latest
    ports:
      - 8080:80
    volumes:
      - ./config/nginx/conf.d/compose_local.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/code/static
      - media_volume:/code/media
    depends_on:
      - web
    networks:
      - nginx_network

networks:
  nginx_network:
    driver: bridge
  db_network:
    driver: bridge

volumes:
  postgres-data:
  static_volume:
  media_volume:
