version: '3'

services:
  db:
    image: kartoza/postgis
    environment:
      - ALLOW_IP_RANGE=0.0.0.0/0
      - POSTGRES_USER=docker
      - POSTGRES_PASS=docker
      - POSTGRES_DBNAME=docker
    networks:
      - db_network
  web:
    build:
      context: .
      dockerfile: Dockerfile.testing
    environment:
      - DJANGO_SETTINGS_MODULE=settings.docker_settings
    command: sleep infinity
    volumes:
      - .:/code
    networks:
      - db_network
      - nginx_network
    depends_on:
      - db
  nginx:
    image: nginx:latest
    ports:
      - 8080:80
    volumes:
      - ./config/nginx/conf.d/compose_local.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web
    networks:
      - nginx_network

networks:
  nginx_network:
    driver: bridge
  db_network:
    driver: bridge
