apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      pod: nginx
  template:
    metadata:
      labels:
        pod: nginx
    spec:
      containers:
        - name: nginx
          image: wischlabs/locality_finder:nginx_latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nginx-static-pv
              mountPath: /code/static
            - name: nginx-media-pv
              mountPath: /code/media

      volumes:
        - name: nginx-static-pv
          persistentVolumeClaim:
            claimName: nginx-static-pvc
        - name: nginx-media-pv
          persistentVolumeClaim:
            claimName: nginx-media-pvc