name: "locality-finder"

django:
  replicaCount: 1

  image:
    repository: wischlabs/locality_finder
    tag: latest
    pullPolicy: Always

  service:
    type: ClusterIP
    port: 80

nginx:
  replicaCount: 1

  image:
    repository: nginx
    tag: stable
    pullPolicy: IfNotPresent

  service:
    type: ClusterIP
    port: 80

postgis:
  replicaCount: 1

  image:
    repository: kartoza/postgis
    tag: latest
    pullPolicy: Always

  service:
    type: ClusterIP
    port: 5432

  db:
    name: docker
    user: docker
    # password: docker

ingress:
  enabled: true
  annotations:
    certmanager.k8s.io/acme-challenge-type: http01
    certmanager.k8s.io/cluster-issuer: letsencrypt-prod-cluster
    kubernetes.io/ingress.class: nginx
  hosts:
    - host: locality-finder-helm.sh4ke.rocks
      paths:
        - path: /
          backend:
            serviceName: nginx-service
            servicePort: 80

  tls:
    - secretName: locality-finder-helm-tls
      hosts:
        - locality-finder-helm.sh4ke.rocks
