version: '3'

services:
  db:
    image: kartoza/postgis
    environment:
      - ALLOW_IP_RANGE=0.0.0.0/0
      - POSTGRES_USER=docker
      - POSTGRES_PASS=docker
      - POSTGRES_DBNAME=docker
    volumes:
      - postgres-data:/var/lib/postgresql/data
  web:
    build: .
    environment:
      - DJANGO_SETTINGS_MODULE=locality_finder.settings.docker_settings
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; python manage.py runserver 0.0.0.0:8080'
    volumes:
      - .:/code
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  postgres-data:
