{{- $fullName := include "helm_chart.fullname" . -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $fullName }}-nginx-configmap
data:
  # When the config map is mounted as a volume, these will be created as files.
  default.conf: |
    upstream gunicorn {
        server {{ $fullName }}-django-service:80;
    }

    server {
        listen 80;
        server_name localhost;

        location / {
            proxy_pass http://gunicorn;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header Host $host;
            proxy_redirect off;

            proxy_connect_timeout       300;
            proxy_send_timeout          300;
            proxy_read_timeout          90m;
            send_timeout                300;

            # Buffering for large data
            proxy_buffering             on;
            proxy_buffer_size           1k;     # buffersize for headers only
            proxy_buffers               24 4k;  # number and size of buffers for proxied responses
            proxy_max_temp_file_size    4096m;

            client_max_body_size        5000m;
        }

        location /static/ {
            alias /code/static/;
        }

        location /media/ {
            alias /code/media/;
        }
    }
