{{- $fullName := include "helm_chart.fullname" . -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $fullName }}-django-configmap
data:
  __init__.py: |
    pass
  prod.py: |
    import os

    from socket import gethostname, gethostbyname
    from ..docker_settings import *

    DEBUG = False

    ALLOWED_HOSTS = [gethostname(), gethostbyname(gethostname()), {{- range $i, $host := .Values.ingress.hosts }}{{if $i}},{{end}}"{{ $host.host }}"{{- end }}, "localhost", "127.0.0.1"]

    SECRET_KEY = os.environ.get('APP_SECRET_KEY', 'unsafe-secret-key')

    DATABASES = {
        'default': {
            'ENGINE': 'django.contrib.gis.db.backends.postgis',
            'NAME': '{{ .Values.postgis.db.name }}',
            'USER': '{{ .Values.postgis.db.user }}',
            'PASSWORD': os.environ.get('POSTGRES_PASSWORD', 'unsafe-postgress-password'),
            'HOST': '{{ $fullName }}-postgis-service',
            'PORT': 5432,
        }
    }

    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.memcached.MemcachedCache',
            'LOCATION': '{{ $fullName }}-memcached-service:11211',
            'TIMEOUT': 300,
            'OPTIONS': {
                'server_max_value_length': 1024 * 1024 * 4,
            }
        }
    }

    # EMail settings (mailjet)
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'  # This is already the default

    EMAIL_PORT = 587  # (alternatively 465)
    EMAIL_HOST = os.environ.get('EMAIL_HOST')
    EMAIL_HOST_USER = os.environ.get('EMAIL_USER')
    EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_PASSWORD')
    EMAIL_USE_TLS = True
