{{- $fullName := include "helm_chart.fullname" . -}}
kind: PersistentVolume
apiVersion: v1
metadata:
  name: {{ $fullName }}-postgres-pv
  labels:
    type: local
spec:
  capacity:
    storage: 6Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /mnt/NAS/k8s_storage/volumes/{{ $fullName }}-postgres-pv
    type: DirectoryOrCreate
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  volumeMode: Filesystem
