{{- $fullName := include "helm_chart.fullname" . -}}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ $fullName }}-nginx-static-pvc
  labels:
    type: local
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  volumeName: {{ $fullName }}-nginx-static-pv
  storageClassName: standard

---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ $fullName }}-nginx-media-pvc
  labels:
    type: local
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  volumeName: {{ $fullName }}-nginx-media-pv
  storageClassName: standard
