apiVersion: v1
kind: Service
metadata:
  name: {{ include "helm_chart.fullname" . }}-memcached-service
  labels:
{{ include "helm_chart.labels" . | indent 4 }}
spec:
  type: {{ .Values.memcached.service.type }}
  ports:
  - protocol: TCP
    port: {{ .Values.memcached.service.port }}
    targetPort: 11211
  selector:
    pod: memcached
    app.kubernetes.io/name: {{ include "helm_chart.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
